import type {
  Reserve,
  PlotProduct,
  GiftAddOn,
  Review,
  GuidedTour,
} from "@/types";

// ─── Reserves ─────────────────────────────────────────────────────────────────
export const RESERVES: Reserve[] = [
  {
    slug: "thingvellir",
    name: "Thingvellir Reserve",
    subtitle: "Where continents divide and history was made",
    description:
      "Set within Iceland's first UNESCO World Heritage Site, where the North American and Eurasian tectonic plates diverge. The ancient Althing parliament, established in 930 AD, met here for centuries.",
    badge: "UNESCO World Heritage",
    badgeVariant: "gold",
    coordinates: { lat: 64.2558, lng: -21.1296 },
    what3words: "///frost.ridge.lava",
    heroImage: "https://images.unsplash.com/photo-1504233529578-6d46baba6d34?w=1200&q=80",
    heroImageAlt: "Aerial view of Thingvellir National Park showing the dramatic rift valley and crystal-clear Þingvallavatn lake in Iceland",
    features: [
      "UNESCO World Heritage Site surroundings",
      "Historic Althing parliament site (est. 930 AD)",
      "Tectonic plate rift valley walks",
      "Crystal-clear Silfra fissure diving",
      "Native birch woodland restoration",
      "Arctic char & brown trout habitat",
    ],
    conservation: "Our Thingvellir Reserve team focuses on native birch reforestation, erosion control along rift walls, and water quality monitoring in Þingvallavatn — one of Iceland's largest and purest lakes.",
  },
  {
    slug: "highland-view",
    name: "Highland View Reserve",
    subtitle: "Rainbow mountains and geothermal wonders",
    description: "Nestled in the spectacular geothermal highlands of Landmannalaugar, famous worldwide for its vivid rhyolite rainbow mountains, natural hot springs, and the legendary start of the Laugavegur trekking route.",
    badge: "Most Popular",
    badgeVariant: "aurora",
    coordinates: { lat: 63.9853, lng: -19.0665 },
    what3words: "///steam.obsidian.moss",
    heroImage: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=80",
    heroImageAlt: "Vivid rainbow rhyolite mountains and geothermal steam vents at Landmannalaugar in Iceland's central highlands",
    features: [
      "World-famous rainbow rhyolite mountains",
      "Natural geothermal hot springs",
      "Start of Laugavegur hiking trail",
      "Arctic fox habitat protection zone",
      "Ptarmigan nesting ground conservation",
      "Unique high-temperature flora ecosystem",
    ],
    conservation: "The Highland View team manages arctic fox den monitoring, invasive lupine control to protect native vegetation, and trail erosion mitigation.",
  },
  {
    slug: "glacier-estate",
    name: "Glacier Estate",
    subtitle: "Europe's greatest ice kingdom",
    description: "In the shadow of Vatnajökull — Europe's largest glacier — within Skaftafell National Park. A realm of dramatic ice formations, glacial rivers, thundering waterfalls, and Jökulsárlón glacier lagoon.",
    badge: "Premium Location",
    badgeVariant: "blue",
    coordinates: { lat: 64.0161, lng: -16.9703 },
    what3words: "///glacier.basalt.flow",
    heroImage: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&q=80",
    heroImageAlt: "Jökulsárlón glacier lagoon at sunset with floating blue icebergs near Vatnajökull National Park, Iceland",
    features: [
      "Adjacent to Vatnajökull — Europe's largest glacier",
      "Skaftafell National Park access",
      "Near Jökulsárlón glacier lagoon",
      "Svartifoss basalt column waterfall nearby",
      "Migratory bird nesting protection",
      "Glacial retreat monitoring programme",
    ],
    conservation: "The Glacier Estate project documents glacial retreat rates, protects bird nesting colonies along outwash plains, and funds research into sub-glacial volcanic activity.",
  },
];

// ─── Plot Products ────────────────────────────────────────────────────────────
export const PLOT_PRODUCTS: PlotProduct[] = [
  {
    id: "plot-1sqft",
    size: "1sqft",
    sqft: 1,
    titleName: "Jarl of Iceland",
    tagline: "Eco Download",
    subtitle: "Instant digital delivery · Zero packaging",
    description: "Own 1 square foot of Icelandic highland and receive everything digitally — perfect for the eco-conscious or anyone who wants instant access.",
    deliveryType: "digital",
    prices: { EUR: 49, USD: 54, GBP: 42 },
    stripePriceId: { EUR: "price_EUR_1sqft_TODO", USD: "price_USD_1sqft_TODO", GBP: "price_GBP_1sqft_TODO" },
    featured: false,
    bestSeller: false,
    accentColor: "from-aurora/20 to-sky-900/20",
    borderColor: "border-aurora/25 hover:border-aurora/50",
    includes: [
      { icon: "📜", label: "Personalised souvenir certificate", description: "A4 PDF, instant download & print-ready" },
      { icon: "👑", label: "Right to style as Jarl / Lord / Lady", description: "Registered trademark souvenir title" },
      { icon: "📍", label: "GPS coordinates & What3Words", description: "Your exact plot location on Earth" },
      { icon: "📱", label: "Owner dashboard access", description: "Digital plot viewer and certificate portal" },
      { icon: "🌐", label: "360° virtual reserve tour", description: "Explore your reserve from anywhere" },
      { icon: "🌱", label: "Plant a Tree certificate", description: "One native Icelandic tree planted in your name" },
      { icon: "📊", label: "Annual conservation report", description: "See your land's ecological impact" },
    ],
    notIncludes: ["Physical gift box", "Printed certificate", "Coaster", "Postal delivery"],
  },
  {
    id: "plot-5sqft",
    size: "5sqft",
    sqft: 5,
    titleName: "Lord / Lady of Iceland",
    tagline: "Luxury Gift Pack",
    subtitle: "Our most popular choice · Beautifully boxed",
    description: "5 square feet of Icelandic highland with a stunning physical luxury gift pack — A3 certificate, reversible coaster, reserve map, bookmark, and app access card.",
    deliveryType: "both",
    prices: { EUR: 69, USD: 79, GBP: 59 },
    stripePriceId: { EUR: "price_EUR_5sqft_TODO", USD: "price_USD_5sqft_TODO", GBP: "price_GBP_5sqft_TODO" },
    featured: true,
    bestSeller: false,
    accentColor: "from-ice-gold/15 to-amber-900/15",
    borderColor: "border-ice-gold/35 hover:border-ice-gold/60",
    badgeText: "Most Popular",
    includes: [
      { icon: "📜", label: "Personalised souvenir certificate", description: "A4 PDF instant + premium A3 printed, framing-ready" },
      { icon: "👑", label: "Right to style as Jarl / Lord / Lady", description: "Registered trademark souvenir title" },
      { icon: "📍", label: "GPS coordinates & What3Words", description: "Your exact plot location on Earth" },
      { icon: "🪨", label: "Reversible Jarl / Lord / Lady coaster", description: "Hand-finished volcanic basalt, reserve-engraved" },
      { icon: "🗺", label: "Iceland reserve map display", description: "Illustrated map with your plot highlighted" },
      { icon: "🔖", label: "'Plant a Tree' bookmark", description: "Photo bookmark with tree-planting certificate" },
      { icon: "📱", label: "App access card", description: "Physical card with dashboard QR code & login" },
      { icon: "🎁", label: "Luxury gift box", description: "Premium box with ribbon, tissue paper & envelope" },
      { icon: "📊", label: "Annual conservation report", description: "See your land's ecological impact each year" },
      { icon: "🚀", label: "Priority tour booking", description: "Jump the queue for guided reserve visits" },
    ],
  },
  {
    id: "plot-10sqft",
    size: "10sqft",
    sqft: 10,
    titleName: "High Jarl of Iceland",
    tagline: "Luxury Gift Pack",
    subtitle: "The ultimate Iceland gift · Collector's edition",
    description: "10 square feet — the grandest expression of your Icelandic legacy. Exclusive collector's certificate, wool wristband, and your name in the dedication register.",
    deliveryType: "both",
    prices: { EUR: 109, USD: 119, GBP: 94 },
    originalPrices: { EUR: 129, USD: 142, GBP: 110 },
    stripePriceId: { EUR: "price_EUR_10sqft_TODO", USD: "price_USD_10sqft_TODO", GBP: "price_GBP_10sqft_TODO" },
    featured: false,
    bestSeller: true,
    accentColor: "from-aurora-violet/20 to-purple-900/20",
    borderColor: "border-aurora-violet/35 hover:border-aurora-violet/60",
    badgeText: "Best Seller",
    includes: [
      { icon: "📜", label: "Exclusive High Jarl collector's certificate", description: "Limited-edition design, A3 printed & A4 PDF" },
      { icon: "👑", label: "Right to style as High Jarl / Lord / Lady", description: "Registered trademark souvenir title" },
      { icon: "📍", label: "GPS coordinates & What3Words", description: "Your exact 10 sq ft plot location on Earth" },
      { icon: "🪨", label: "Reversible High Jarl coaster", description: "Premium volcanic basalt, engraved both sides" },
      { icon: "🗺", label: "Iceland reserve map display", description: "Large-format illustrated reserve map" },
      { icon: "🔖", label: "'Plant a Tree' bookmark", description: "Bookmark with tree-planting certificate" },
      { icon: "📱", label: "App access card", description: "Physical card with dashboard QR code" },
      { icon: "🎁", label: "Luxury collector's gift box", description: "Collector-grade presentation with ribbon" },
      { icon: "🧶", label: "Icelandic wool wristband", description: "Sustainably sourced natural Icelandic wool" },
      { icon: "📋", label: "Dedication register inscription", description: "Your name permanently recorded in the reserve register" },
      { icon: "📰", label: "Annual conservation newsletter", description: "Exclusive updates from the reserve warden" },
      { icon: "🚀", label: "Lifetime priority tour access", description: "First access to all guided reserve experiences" },
    ],
  },
  {
    id: "plot-bundle-2person",
    size: "bundle-2person",
    sqft: null,
    titleName: "Dual Jarls of Iceland",
    tagline: "Couples Bundle",
    subtitle: "Two side-by-side plots · Perfect for couples & friends",
    description: "Two adjacent 5 sq ft plots, two luxury gift packs personalised for each recipient. The perfect couples gift — certified highland neighbours.",
    deliveryType: "both",
    prices: { EUR: 119, USD: 132, GBP: 102 },
    originalPrices: { EUR: 138, USD: 158, GBP: 118 },
    stripePriceId: { EUR: "price_EUR_bundle_TODO", USD: "price_USD_bundle_TODO", GBP: "price_GBP_bundle_TODO" },
    featured: false,
    bestSeller: false,
    accentColor: "from-pink-900/20 to-rose-900/15",
    borderColor: "border-pink-500/25 hover:border-pink-500/50",
    badgeText: "Save €19",
    includes: [
      { icon: "💑", label: "Two personalised certificates", description: "Adjacent plot references, one per recipient" },
      { icon: "👑", label: "Two noble souvenir titles", description: "Each person chooses Jarl / Lord / Lady" },
      { icon: "📍", label: "Adjacent GPS coordinates", description: "Certified side-by-side plots in the same reserve" },
      { icon: "🪨", label: "Two reversible coasters", description: "One per recipient, reserve-engraved" },
      { icon: "🗺", label: "Shared reserve map", description: "Both plots highlighted on one illustrated map" },
      { icon: "🔖", label: "Two 'Plant a Tree' bookmarks", description: "One native tree planted per recipient" },
      { icon: "📱", label: "Two app access cards", description: "Separate dashboard logins for each plot owner" },
      { icon: "🎁", label: "Two luxury gift boxes", description: "Individually addressed, ready to gift" },
      { icon: "💌", label: "Personalised couple's gift card", description: "Bespoke message from you to both recipients" },
    ],
  },
];

// ─── Gift Add-Ons ─────────────────────────────────────────────────────────────
export const GIFT_ADDONS: GiftAddOn[] = [
  { id: "adopt-horse", name: "Adopt an Icelandic Horse", description: "Personalised photo, biography card, and annual welfare update.", icon: "🐴", price: 29, priceLabel: "€29/year", annual: true },
  { id: "adopt-puffin", name: "Adopt an Atlantic Puffin", description: "Support puffin colony conservation. Includes adoption certificate.", icon: "🦜", price: 19, priceLabel: "€19/year", annual: true },
  { id: "adopt-fox", name: "Adopt an Arctic Fox", description: "Help protect highland habitat and monitor population recovery.", icon: "🦊", price: 24, priceLabel: "€24/year", annual: true },
  { id: "adopt-eagle", name: "Adopt a White-tailed Eagle", description: "Support Iceland's most majestic raptor. Includes nest camera access.", icon: "🦅", price: 22, priceLabel: "€22/year", annual: true },
  { id: "coaster", name: "Extra Volcanic Basalt Coaster", description: "Hand-finished coaster engraved with reserve name and GPS coordinates.", icon: "🪨", price: 12, priceLabel: "€12", annual: false },
  { id: "map", name: "Reserve Explorer Map", description: "Large-format illustrated topographic map on parchment paper.", icon: "🗺", price: 9, priceLabel: "€9", annual: false },
];

// ─── Reviews ──────────────────────────────────────────────────────────────────
export const REVIEWS: Review[] = [
  { id: "1", author: "Sophie Müller", location: "Berlin, Germany", rating: 5, date: "2024-11-15", text: "Bought this for my husband's birthday and he absolutely loved it. The certificate arrived beautifully packaged and looked incredible framed on the wall. He now insists on being called Lord James at dinner parties!", verified: true, initials: "SM", avatarColor: "from-purple-500/20 to-violet-500/20 text-violet-300" },
  { id: "2", author: "Thomas Kowalski", location: "New York, USA", rating: 5, date: "2024-10-28", text: "As someone who's visited Iceland three times, this hits differently. Knowing I have a tiny slice of Landmannalaugar — and that it's being cared for — is genuinely moving. The map is gorgeous.", verified: true, initials: "TK", avatarColor: "from-cyan-500/20 to-sky-500/20 text-sky-300" },
  { id: "3", author: "Erika Lindström", location: "Stockholm, Sweden", rating: 5, date: "2024-12-01", text: "Gifted the 5 sq ft pack to my dad who's obsessed with Norse mythology. He was in tears. The quality of everything — certificate, box, bookmarks — is premium.", verified: true, initials: "EL", avatarColor: "from-emerald-500/20 to-teal-500/20 text-emerald-300" },
  { id: "4", author: "Björn Arnarsson", location: "Reykjavík, Iceland", rating: 5, date: "2024-09-14", text: "Even as an Icelander, this made me smile! I bought the Glacier Estate plot. The conservation mission is real and important.", verified: true, initials: "BA", avatarColor: "from-amber-500/20 to-yellow-500/20 text-amber-300" },
  { id: "5", author: "Mei Watanabe", location: "Tokyo, Japan", rating: 5, date: "2024-11-30", text: "The What3Words feature blew my mind. I found my exact square foot on Google Earth. It's a tiny sliver of mossy highland, but it's MY tiny sliver. Magical.", verified: true, initials: "MW", avatarColor: "from-pink-500/20 to-rose-500/20 text-pink-300" },
  { id: "6", author: "Carlos Reyes", location: "Madrid, Spain", rating: 5, date: "2024-12-10", text: "Best Christmas gift I've ever given. My wife is now officially Lady Isabella of the Icelandic Highlands. She has changed her email signature.", verified: true, initials: "CR", avatarColor: "from-red-500/20 to-orange-500/20 text-red-300" },
];

// ─── Guided Tours ─────────────────────────────────────────────────────────────
export const GUIDED_TOURS: GuidedTour[] = [
  { id: "thingvellir-walk", name: "Thingvellir Conservation Walk", reserve: "thingvellir", duration: "4 hours", groupSize: "Max 12", difficulty: "Easy–Moderate", description: "A guided walk through the historic rift valley, ending at the reserve. Includes geological briefing and conservation update.", price: 89, image: "https://images.unsplash.com/photo-1504233529578-6d46baba6d34?w=800&q=80", imageAlt: "Hikers walking along Thingvellir rift valley in Iceland" },
  { id: "highland-expedition", name: "Highland Wilderness Expedition", reserve: "highland-view", duration: "8 hours", groupSize: "Max 8", difficulty: "Moderate", description: "A full-day adventure across the rainbow mountains with a soak in natural hot springs and exclusive reserve briefing.", price: 149, image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80", imageAlt: "Group of hikers traversing colourful rhyolite mountains at Landmannalaugar Iceland" },
  { id: "glacier-walk", name: "Glacier Estate Ice Walk", reserve: "glacier-estate", duration: "Full day", groupSize: "Max 10", difficulty: "Moderate–Hard", description: "Walk on Europe's largest glacier with a certified guide, visit the reserve and Jökulsárlón lagoon. All gear included.", price: 195, image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80", imageAlt: "Guided ice walk on Vatnajokull glacier Iceland" },
];

// ─── Site constants ───────────────────────────────────────────────────────────
export const SITE = {
  name: "Icelandic Titles",
  tagline: "Become a Jarl, Lord or Lady of the Icelandic Highlands",
  description: "Buy a souvenir plot of land in a breathtaking Icelandic nature reserve and style yourself as Jarl, Lord or Lady of the Icelandic Highlands. Receive a personalised certificate and help restore Iceland's landscapes.",
  url: "https://icelandictitles.com",
  email: "hello@icelandictitles.com",
  phone: "+354 555 0100",
  address: { street: "Laugavegur 15", city: "Reykjavík", postcode: "101", country: "Iceland" },
  social: { instagram: "https://instagram.com/icelandictitles", facebook: "https://facebook.com/icelandictitles", tiktok: "https://tiktok.com/@icelandictitles", pinterest: "https://pinterest.com/icelandictitles" },
  trustpilot: { rating: 4.8, reviewCount: 22147, url: "https://trustpilot.com/review/icelandictitles.com" },
} as const;
